#!/bin/bash

# automatically change location settings based on SSID
exec &>/usr/local/var/log/locationchanger.log
# redirect all IO to /dev/null (comment this out if you want to debug)
# exec 1>/dev/null 2>/dev/null

# take a little breather before we get data
sleep 1

# get current SSID
SSID=`networksetup -getairportnetwork en0 | cut -d ':' -f 2 | cut -c 2-`

# get location information
LOCATION_NAMES=`networksetup -listlocations`
CURRENT_LOCATION=`networksetup -getcurrentlocation`

# check for office SSIDs
if [[ "$SSID" =~ "GrayLoon" ]]; then
  NEW_LOCATION="Gray Loon"
else
  # use Other if no matching SSID found
  if echo Other | grep -q "$LOCATION_NAMES"; then
    NEW_LOCATION=Other
  else
    echo "Other location was not found!"
    echo "The following locations are available:"
    echo "$LOCATION_NAMES"
  fi
fi

# switch the location
if [ "x$NEW_LOCATION" == "x$CURRENT_LOCATION" ]; then
    echo "Nothing to do"
else
    echo "Changing to $NEW_LOCATION"
    networksetup -switchtolocation "$NEW_LOCATION"
fi
